version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - .:/rails-app
    environment:
      DATABASE_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    
